apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
      
name: logs
      image: microsservicoslogs
      ports:
containerPort: 4006  
    env:
name: PORT
    value: "4006"  